### ISSUE TITLE
Need Offline build transaction and sign

### ISSUE THREAD

**Issue by liuzhenLz** [farukterzioglu/HDWallet#47]
The way to create transactions is not completely offline, which is a serious problem. When signing, you cannot guarantee whether the contents of the trading partner are not tampered with.

**Comment by liuzhenLz** [comment]
HDWallet.Tron

**Comment by farukterzioglu** [comment]
Transaction construction is out of scope of this project. But you can sign offline with this project. 
Sample at [here](https://github.com/farukterzioglu/HDWallet/tree/master/src/HDWallet.Tron) it using `wallet/createtransaction` from Tron node but instead of this you can construct your transaction offline and sign with this SDK. 
This project only meant to be used for signing. 

Constructing Tron transaction from code must not be hard, you only need to create a specific object with correct data. For example response of online helper endpoint;

```
{
    "visible": true,
    "txID": "a18e1d3482e9c4fc5788c945c8a9a9ffe98865258f19570a3095d1b32dff6e07",
    "raw_data": {
        "contract": [
            {
                "parameter": {
                    "value": {
                        "amount": 10000,
                        "owner_address": "TZ7aDU6GS4NMUQRB3ixVg6TQyR739tUyU6",
                        "to_address": "TEmqPQsgkdHijWkLX6sxJRTcaRVfBTMGpn"
                    },
                    "type_url": "type.googleapis.com/protocol.TransferContract"
                },
                "type": "TransferContract"
            }
        ],
        "ref_block_bytes": "2d7e",
        "ref_block_hash": "20731dc82dcef2e4",
        "expiration": 1646976951000,
        "timestamp": 1646976894017
    },
    "raw_data_hex": "0a022d7e220820731dc82dcef2e440d8c5e7bbf72f5a66080112620a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412310a1541fddfede225bb429457cdcc6cd5bcaa42b3eea3b512154134b202a87882c4f87d214b7f30b1c6b6804365f818904e70c188e4bbf72f"
}
```
You can create this object oflline and sign it offline.

**Comment by liuzhenLz** [comment]
Thank you very much, but from the perspective of mobile clients, I still hope that the project itself supports offline build transactions, just like nethereum

**Comment by liuzhenLz** [comment]
The actual use experience will be much better

**Comment by farukterzioglu** [comment]
Nethereum is full fledged solution for Ethereum. 
This projects only aims to create sub wallets from a master key. 
Since this project creates a wallet (hd or non-hd) it can also sign a **message** (not a transaction)
Transaction creation and signing can be implemented outside of this project, but for message signing it can use wallet created by this project.

**Comment by farukterzioglu** [comment]
> The actual use experience will be much better
Sure it will be much better because user won't need to write code to construct transaction, it will be already written. 
Instead of using a ready solution, someone can write it and open source it. Still it won't be included in here since it is totally different scope.

But users would also need to write code for generating hierarchical deterministic wallet, and this project handle these for users.

**Comment by farukterzioglu** [comment]
This request is out of scope of this repository. 
Closing this.
